spring:
  application:
    name: ntfy-app-api

  # JPA and Hibernate configuration
  datasource:
    url: jdbc:postgresql://192.168.10.32:5432/demo_api
    username: demo
    password: Demo2025
    driver-class-name: org.postgresql.Driver
    hikari:

      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: BookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ntfy_app
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: false

    open-in-view: false

  webflux:
    base-path: /api

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
    min-response-size: 2KB

# Database schema configuration
database:
  schema:
    default: ntfy-app
    allowed-schemas: public,ntfy-app,tenant2,staging
    header-name: X-Schema
    query-param-name: schema

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.data: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.demo.ntfyappapi.service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

# Custom application properties
app:
  approval:
    allowed-statuses: APPROVED,REJECTED,PENDING_REVIEW
    auto-approve-threshold: 3
    notification:
      enabled: true
      email-template: approval-notification.html

  security:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type
      max-age: 3600

  cache:
    enabled: true
    ttl-seconds: 300

  # For multi-tenancy and schema switching
  tenant:
    schema-based: true
    default-tenant: ntfy-app